name: hello
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  uuid: ^4.4.2
  path_provider: ^2.1.4
  image_picker: ^1.2.0
  file_picker: ^10.3.2
  mongo_dart: 0.10.5
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^25.1.39
  path: ^1.9.0
  shared_preferences: ^2.2.2
  lottie: ^2.6.0
  http: ^1.1.0
  url_launcher: ^6.1.10
  dio: ^5.2.0
  permission_handler: ^10.4.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/UploadDocument.png
    - assets/PickFromCamera.png
    - assets/Reports.png
    - assets/Prescription.png
    - assets/2851468.png
    - assets/Insurance12.png
    - assets/AiAllyLogo.png
    - assets/BloodReport.png
    - assets/HospitalBill.png
    - assets/LoadingClock.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
